/*
 * This Java source file was generated by the Gradle 'init' task.
 * https://github.com/openjfx/samples/blob/master/HelloFX/Gradle/hellofx/src/main/java/HelloFX.java
 */
package helloworldwithgradle;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage stage) {
        Scene scene = new LoginScene(new VBox(), 640, 480);
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }

}

/*
Coesão e Acoplamento talvez sejam as características mais importantes de qualquer sistema.

Sendo a "Coesão" um conceito de grau onde algo como uma classe ou método, po exemplo, deve ter apenas uma única responsabilidade e realizá-la de maneira satisfatória.

Também apresentando o "Acoplamento", que possui um contexto onde, esse "algo" leva uma base de que depende de terceiros para seu funcionamento, similar a algo como "A união faz a força".
*/