/*
 * This Java source file was generated by the Gradle 'init' task.
 * https://github.com/openjfx/samples/blob/master/HelloFX/Gradle/hellofx/src/main/java/HelloFX.java
 */
package helloworldwithgradle;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage stage) {
        Scene scene = new LoginScene(new VBox(), 640, 480);
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }

}

/*
Coesão e Acoplamento são princípios antigos e muito utilizados dentro da engenharia de software.

Sendo a "Coesão" um conceito para determinada classe, onde esta deve seguir uma única tarefa/atividade/processo, de maneira individual, satisfatória e não deve assumir
responsabilidades que não são suas.

O "Acoplamento" é a dependência entre as classes para funcionarem, mas em excesso pode trazer muitos problemas, sendo este um cenário similar ao não coeso.

Ref: https://www.devmedia.com.br/entendendo-coesao-e-acoplamento/18538
*/